//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.521.0.
namespace LiquidTestReports.Core.Junit
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("failure", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("failure", Namespace="")]
    public partial class Failure
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("message")]
        public string Message { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("error", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("error", Namespace="")]
    public partial class Error
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("message")]
        public string Message { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("properties", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("properties", Namespace="")]
    public partial class Properties
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Property> _property;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Property> Property
        {
            get
            {
                return this._property;
            }
            private set
            {
                this._property = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Properties" /> class.</para>
        /// </summary>
        public Properties()
        {
            this._property = new System.Collections.ObjectModel.Collection<Property>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("property", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("property", Namespace="")]
    public partial class Property
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("testcase", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("testcase", Namespace="")]
    public partial class Testcase
    {
        
        [System.Xml.Serialization.XmlElementAttribute("skipped", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Skipped { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Error> _error;
        
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Error> Error
        {
            get
            {
                return this._error;
            }
            private set
            {
                this._error = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Error collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorSpecified
        {
            get
            {
                return (this.Error.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Testcase" /> class.</para>
        /// </summary>
        public Testcase()
        {
            this._error = new System.Collections.ObjectModel.Collection<Error>();
            this._failure = new System.Collections.ObjectModel.Collection<Failure>();
            this._system_Out = new System.Collections.ObjectModel.Collection<string>();
            this._system_Err = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Failure> _failure;
        
        [System.Xml.Serialization.XmlElementAttribute("failure", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Failure> Failure
        {
            get
            {
                return this._failure;
            }
            private set
            {
                this._failure = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Failure collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FailureSpecified
        {
            get
            {
                return (this.Failure.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _system_Out;
        
        [System.Xml.Serialization.XmlElementAttribute("system-out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<string> System_Out
        {
            get
            {
                return this._system_Out;
            }
            private set
            {
                this._system_Out = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the System_Out collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool System_OutSpecified
        {
            get
            {
                return (this.System_Out.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _system_Err;
        
        [System.Xml.Serialization.XmlElementAttribute("system-err", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<string> System_Err
        {
            get
            {
                return this._system_Err;
            }
            private set
            {
                this._system_Err = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the System_Err collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool System_ErrSpecified
        {
            get
            {
                return (this.System_Err.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("assertions")]
        public string Assertions { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("time")]
        public string Time { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("classname")]
        public string Classname { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public string Status { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("testsuite", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("testsuite", Namespace="")]
    public partial class Testsuite
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Property> _properties;
        
        [System.Xml.Serialization.XmlArrayAttribute("properties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Property> Properties
        {
            get
            {
                return this._properties;
            }
            private set
            {
                this._properties = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Properties collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertiesSpecified
        {
            get
            {
                return (this.Properties.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Testsuite" /> class.</para>
        /// </summary>
        public Testsuite()
        {
            this._properties = new System.Collections.ObjectModel.Collection<Property>();
            this._testcase = new System.Collections.ObjectModel.Collection<Testcase>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Testcase> _testcase;
        
        [System.Xml.Serialization.XmlElementAttribute("testcase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Testcase> Testcase
        {
            get
            {
                return this._testcase;
            }
            private set
            {
                this._testcase = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Testcase collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestcaseSpecified
        {
            get
            {
                return (this.Testcase.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("system-out", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string System_Out { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("system-err", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string System_Err { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("tests")]
        public string Tests { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("failures")]
        public string Failures { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("errors")]
        public string Errors { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("time")]
        public string Time { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("disabled")]
        public string Disabled { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("skipped")]
        public string Skipped { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("timestamp")]
        public string Timestamp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("hostname")]
        public string Hostname { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("package")]
        public string Package { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.521.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("testsuites", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("testsuites", Namespace="")]
    public partial class Testsuites
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Testsuite> _testsuite;
        
        [System.Xml.Serialization.XmlElementAttribute("testsuite", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Testsuite> Testsuite
        {
            get
            {
                return this._testsuite;
            }
            private set
            {
                this._testsuite = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Testsuite collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestsuiteSpecified
        {
            get
            {
                return (this.Testsuite.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Testsuites" /> class.</para>
        /// </summary>
        public Testsuites()
        {
            this._testsuite = new System.Collections.ObjectModel.Collection<Testsuite>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("time")]
        public string Time { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("tests")]
        public string Tests { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("failures")]
        public string Failures { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("disabled")]
        public string Disabled { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("errors")]
        public string Errors { get; set; }
    }
}
